version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "portfolio"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-x0ar5uayh9wp"
s3_prefix = "portfolio"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
image_repositories = []
disable_rollback = true


["'".deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
