version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::801328174059:user/aws-sam-cli-managed-prod-pipeline-reso-PipelineUser-kmn0rvW5ClRd"
permissions_provider = "AWS IAM"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::801328174059:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-5G2zYHNYiUPV"
cloudformation_execution_role = "arn:aws:iam::801328174059:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-DygQerfWakbx"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-5swr0xqxqqgu"
image_repository = ""
region = "us-east-1"
